apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: psed_visualizer
  annotations:
    github.com/project-slug: Nigglea/psed_visualizer
spec:
  type: visualization tool
  lifecycle: prototype
  owner: Nigglea
